version: '3.8'
services:
  web:
    container_name: homelab-app-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
